name: caominhtien_61cntt2
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  flutter_slidable: ^1.2.0
  rflutter_alert: ^2.0.4
  shared_preferences: ^2.0.13
  oxford_dictionary: ^2.0.3
  http: ^0.13.4
  xml2json: ^5.3.2
  path_provider: ^2.0.9
  webview_flutter: ^3.0.2
  webview_flutter_plus: ^0.3.0+2
  sqflite: ^2.0.2+1
  fluttercontactpicker: ^4.6.0
  flutter_contact: ^0.9.1+8
  url_launcher: ^6.1.2
  device_info_plus: ^3.2.3
  network_info_plus: ^2.1.3
  battery_info: ^1.1.1
  flutter_blue: ^0.8.0
  flutter_reactive_ble: ^5.0.2
  firebase_core: ^1.17.0
  cloud_firestore: ^3.1.15
  firebase_database: ^9.0.14
  image_picker: ^0.8.5+3
  firebase_storage: ^10.2.16
  firebase_messaging: ^11.4.0
  flutter_local_notifications: ^9.5.3+1
  flutter_app_badger: ^1.4.0
  badges: ^2.0.2
  font_awesome_flutter: ^10.1.0
  firebase_auth: ^3.3.19
  google_sign_in: ^5.3.2
  camera: ^0.9.7+1
#  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/photoAlbum/
    - assets/gridView/
    - assets/weather/
    - assets/cpu_z/
    - assets/login_page/
#    - packages/rflutter_alert/assets/images/